title: Rosemary Wang
description: About me, links to speaker slides and recordings.

author:
  name: Rosemary Wang

social-network-links:
  github: joatmon08
  twitter: joatmon08
  linkedin: rosemarywang
  twitch: joatmon08
theme: jekyll-theme-cayman