title: Rosemary Wang
description: About me, links to speaker slides and recordings.

navbar-links:
  About Me: "about"
  Speaking: "speaking"
  Writing: "writing"
  Blog: "https://medium.com/@joatmon08"

author:
  name: Some Person

social-network-links:
  github: joatmon08
  twitter: joatmon08
  linkedin: rosemarywang
  twitch: joatmon08
theme: jekyll-theme-hacker